feat(integration): Add initial "integration tests"
loculus-project/loculus pull request #3121
Opened 2024-10-29 22:11 UTC by theosanderson

We decided we should have tests that will ultimately test the preprocessing pipelines and ingest. I propose to call these "integration tests" just to have a new name. Unlike other website-related tests they will live in their own top level directory. 

My idea for this is that we should try to see how far we can get with these tests only interacting with Loculus in ways that users would. This means primarily the website, though as we add say a CLI it would also include that. So, setting up test data etc. can all be done through the website at least until we find that that is being flaky or too slow.

2024-10-30 07:39 UTC, fengelniederhammer commented on deploy.py
> +        parameters += ["--set", "auth.verifyEmail=false"]
Why don't we put that in the e2e values.yaml? Or even in the real values.yaml?

2024-10-30 07:39 UTC, fengelniederhammer commented on integration-tests/run.sh
It's called run, but it doesn't run the tests? :)

2025-01-10 17:41 UTC, theosanderson commented on deploy.py
> +        parameters += ["--set", "auth.verifyEmail=false"]
👍

2025-01-13 12:09 UTC, fhennig commented
I have this on my list, will look into it later today or tomorrow the latest!

2025-01-14 13:18 UTC, fhennig requested changes
Very cool! The way the tests are written now is very easy to read, looks great! I have a couple remarks, but nothing major.

2025-01-14 13:26 UTC, theosanderson commented on integration-tests/playwright.config.ts
> +// dotenv.config({ path: path.resolve(__dirname, '.env') });
This is basically how Playwright sets up a project by default. My own feeling is that the hints left by default configurations can be useful, e.g. so we remember that we could use dotenv (which I wouldn't otherwise), but I'm happy to remove.

2025-01-14 13:31 UTC, theosanderson commented on integration-tests/start-server.sh
> + python ../.github/scripts/wait_for_pods_to_be_ready.py
Thanks - I think I'll leave this for the moment

2025-01-14 13:35 UTC, theosanderson commented on integration-tests/playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
Agreed - fixed

2025-01-14 13:36 UTC, theosanderson commented on integration-tests/tests/pages/auth.page.ts
> +    await this.page.getByLabel('Password', { exact: true }).press('Tab');
:+1: I left out the tab

2025-01-14 13:38 UTC, theosanderson commented on integration-tests/tests/pages/auth.page.ts
> +    await this.page.goto('http://localhost:3000/');
:+1:

2025-01-14 13:40 UTC, theosanderson commented on integration-tests/tests/specs/features/authenticated.spec.ts
> +  });
In due course there will be versions of this with stuff inside, but yes it does check the fixture,

2025-01-14 14:56 UTC, fhennig commented on integration-tests/playwright.config.ts
> +// dotenv.config({ path: path.resolve(__dirname, '.env') });
I see! No I'm fine with leaving it then 👌

2025-01-14 16:04 UTC, theosanderson commented on integration-tests/tests/fixtures/auth.fixture.ts
> +});
Thanks, yes!

2025-01-14 16:26 UTC, theosanderson commented on integration-tests/tests/config/test.config.ts
> +const config: PlaywrightTestConfig = {
Thanks a lot - I have no recollection of how I ended up with this - probably prompted by an LLM when fighting with some problem. I've got rid of it and things seem fine and the same number of tests run 👍

2025-01-14 16:31 UTC, theosanderson commented on integration-tests/tests/fixtures/auth.fixture.ts
> +  testAccount: async ({}, use) => {
I did https://github.com/loculus-project/loculus/pull/3121/commits/9e9122e382d9b00d9f9b8b5f34469e5b9343e3b1 - not sure if that's exactly what you had in mind

2025-01-14 16:41 UTC, theosanderson commented
Great comments - thanks!

2025-01-15 09:37 UTC, fhennig commented on integration-tests/tests/fixtures/auth.fixture.ts
> +  testAccount: async ({}, use) => {
Yes I wasn't very explicit, I thought about typing the function signature, but this has the same effect! 👌

2025-01-15 09:41 UTC, fhennig approved these changes
L very GTM! 😄 🚀

2025-01-15 10:44 UTC, merged