Improve review load (WIP)
loculus-project/loculus pull request #3189
Opened 2024-11-07 12:48 UTC by fhennig

resolves #

preview URL:

### Summary

### Screenshot

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

2024-11-11 13:02 UTC, fhennig commented
cool, the test went through!

2024-11-15 13:03 UTC, theosanderson commented on backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
> +        "Issues where data is not necessarily wrong, but the user might want to look into those warnings.",
```suggestion
        "Issues where data is not necessarily wrong, but there are warning messages from the pipeline that the user might want to look into.",
```

(just sounded weird to me before)

2024-11-15 13:10 UTC, theosanderson requested changes
Sorry for the slow review, and sorry that this issue wasn't fully specced. Unfortunately I think the PR at present is problematic as it could use 20 MB of bandwidth every few seconds.

2024-11-15 13:10 UTC, theosanderson commented on website/src/types/backend.ts
I think that if we were to make the changes in this PR we need to not send sequences in the endpoint used on the review page. This is is because:

- sequences for some viruses are 200 kb, 100 per page = 20 MB, polling constantly = a lot of bandwidth

We may want to delay making any change here for now for simplicity to avoid having to add extra types etc.

2024-11-18 11:10 UTC, fhennig commented
Thanks for bringing that up Theo! I didn't realize that the sequences were in there too. In that case you're right, I think it's best to shelve this again for now, as we have something that's currently working and we initially thought that this might be a "quick win".

I'm closing this for now.

2024-11-18 11:10 UTC, closed without merging

2024-11-21 03:52 UTC, corneliusroemer commented
It's not really working well though. Load times of 15+ seconds if there are 15k sequences aren't really acceptable.

2024-11-21 08:46 UTC, fhennig commented
Maybe worth discussing next monday? pinging @chaoran-chen 

I haven't looked into it that much, but it seems like it might be a good idea to try and redesign it so we can send the metadata withtout the raw sequence data - which is the largest chunk of the data in my understanding. Maybe us 3 (Theo, Cornelius and me) can have a refinement meeting on this ticket and see what would need to get done for this, and then we can decide if the amount of work is something we want to put in now or later.

2024-11-21 09:06 UTC, chaoran-chen commented
Sounds good, I added it to the agenda for next Monday.

2024-11-21 17:22 UTC, corneliusroemer commented
There might be multiple issues here:
- sending sequence data (totally unnecessary) - but that shouldn't itself cause that much of a slowdown alone especially as many of the sequences loaded for WNV are very short there isn't that much data to be transferred in practice.
- slow performance of backend endpoint even for small number of sequences, maybe due to a sort or something like that in the SQL, see e.g. #1612
- we also send lots of nulls for processed data which is wasteful, we only care about the non-null fields (can assume nulls for the others)

2024-11-21 17:43 UTC, theosanderson commented
The issue might be _uncompressing_ the sequence data rather than sending it (we at most send a page's worth of data IIUC)