feat(website): Column remapping when submitting metadata files
loculus-project/loculus pull request #3478
Opened 2024-12-23 12:28 UTC by fhennig

resolves #

preview URL:

### Summary

### Screenshot

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

2025-01-08 13:36 UTC, theosanderson commented
I think the logic needs to be reversed, with a row for each "Column in your file", for which you can choose the inputField to map to. This is because often the uploaded file may only have like 4 columns from the selection.

2025-01-08 14:14 UTC, fhennig commented
ok!

2025-01-08 15:58 UTC, chaoran-chen commented
What happens if you have a column that is not mentioned in the `inputFields`? The API/backend would accept it and leave it to the pipeline to decide what to do with it. With this PR, would the website now reject files that would still be possible to submit directly through the API?

2025-01-08 16:01 UTC, fhennig commented
Files are generally not rejected.

The column remapping however would force you to either map a column to a column that is specified in the input fields, or to just not include the column.

You can also just ignore column remapping altogether, and still submit files with whatever structure you like to the backend.

2025-01-08 16:03 UTC, chaoran-chen commented
Ah, so it's possible to skip the remapping? (Sorry, I haven't tried out the feature yet!)

2025-01-08 16:07 UTC, fhennig commented
yes. Remapping is only done if you click the button to add a column mapping. I also took care to not decompress TSV files if no column mapping is to be applied! (I still need to test if this actually works the way I implemented it)

2025-01-08 16:26 UTC, fhennig commented
TODO replace `getMetadataTemplateFields` usage with using all possible input fields.

2025-01-10 10:21 UTC, rneher commented
I just tried this on the preview. 

Overall, the flow seems sensible to me. But there were a few things I stumbled on. 

 - we effectively do not have a required metadata format anymore. So the text on the left needs adjusting
 - it would be good if the button "Column mapping" had help tool-tip or similar that explains what this does (e.g. "If you are not using our metadata template, this allows you to map columns in your file to the fields expected by the database")
 - It was quite hard to find the entries in the long list. the list seems vaguely alphabetical, but important fields like "collection date" were all the way down in a seemingly random place
 



![image](https://github.com/user-attachments/assets/ad6aba22-e222-4f17-aadc-399737e7c56c)

2025-01-10 10:22 UTC, rneher commented
Ideally, I think we should have required columns at the top of the list. And if easy to do, we could highly columns that are already selected with a different background color or similar?

2025-01-10 10:23 UTC, rneher commented
beyond that, I think it would be good to merge this in asap after some testing.

2025-01-13 14:03 UTC, fhennig commented
I checked about "And if easy to do, we could highly columns that are already selected with a different background color or similar?" -> Unfortunately the native select element options cannot be styled. I experimented with putting UTF-8 symbols with the text but wasn't happy. I think it's quite helpful though to see which ones are already mapped. A proper solution would, however, involve getting rid of the native select element. Probably not for this PR.

2025-01-14 15:40 UTC, fhennig commented
Ok, I decided to use ListBox by headlessUI since we already use that for the Autocomplete Field as well, and now I have this:

<img width="511" alt="image" src="https://github.com/user-attachments/assets/de5e8ac2-8a44-46ab-8485-d177068b1f4e" />

2025-01-14 19:57 UTC, anna-parker commented on website/src/utils/groupFieldsByHeader.ts
> +    definition: 'TODO',
Hmm... so we should actually make this customizable for each `name` and `accessionPrefix` (see values.yaml) - sorry for complicating this!

 But users would really need to see an example accession and we have a different `accessionPrefix` in Loculus and Pathoplexus. 
```suggestion
    definition: 'The {name, e.g. Loculus} accession (without version) of the sequence you would like to revise',
    guidance: ''
    example: '{accessionPrefix, e.g. LOC_}000P97Y`
```
You can probably leave guidance empty I think with an example and a definition this should be quite clear :-)

2025-01-15 09:34 UTC, fhennig commented on website/src/utils/groupFieldsByHeader.ts
> +    definition: 'TODO',
I moved getGroupedInputFields into the `config.ts`, so it's easier to get these properties. Let me know what you think! https://github.com/loculus-project/loculus/pull/3478/commits/84c843ca3b9aebb6502ff94649345bf6792af67b

2025-01-15 23:58 UTC, chaoran-chen commented on website/package.json
> +        "string-similarity-js": "^2.1.4",
Given that the library doesn't seem to be actively maintained (last commit 4 years ago, and not many stars) and just consists of [one file](https://github.com/stephenjjbrown/string-similarity-js/blob/master/src/string-similarity.ts), I wonder whether it would be better to simply copy over the code (of course with a reference back to the repository) instead of including the package to reduce the surface for supply chain attacks.

2025-01-16 00:02 UTC, chaoran-chen commented on website/src/components/Submission/DataUploadForm.tsx
> +    // can be null; if null -> don't apply mapping.
```suggestion
    // The columnMapping can be null; if null -> don't apply mapping.
```

To avoid potential misunderstanding to which line this comment belongs to

2025-01-16 08:12 UTC, anna-parker commented
@fhennig the preview is broken, maybe you need to rebase?

2025-01-16 08:41 UTC, fhennig commented
@anna-parker preview working again!

2025-01-16 08:58 UTC, anna-parker commented
I was just testing and I cannot upload the test data anymore (even if I do not do any mapping), I tried uploading the example ebola data here: https://github.com/pathoplexus/example_data but it fails, I checked and this still works on main: 
![image](https://github.com/user-attachments/assets/055e2c55-d6b2-41cb-b6a8-a437fa354b8d)

2025-01-16 10:38 UTC, fhennig commented
oh no :( Thanks for finding that Anna!

2025-01-16 17:40 UTC, chaoran-chen submitted a review, later dismissed

2025-01-16 17:40 UTC, chaoran-chen commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +    public update(newSourceColumns: string[], inputFields: InputField[]): ColumnMapping {
Would it be better/more consistent to call the second parameter `newInputFields`?

2025-01-16 17:40 UTC, chaoran-chen commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +        const inputRows = text.trim().split('\n');
Oh, you're not using a full TSV parser? This would cause problems if there is a multiline cell which, I think, is a reasonable use case for fields like version comment. The following file doesn't work:

```
submissionId	versionComment	geoLocCountry	sampleCollectionDate
test1	"Paragraph 1...

...and paragraph 2"	USA	2011-07-18
test2	"Paragraph 1...

...and paragraph 2"	USA	2011-07-18
```

2025-01-17 09:57 UTC, anna-parker requested changes
Hey Felix - this is looking really great I found one bug if you could fix it - I was also wondering if you could add a couple more desired fields to the values.yaml to check this works correctly - this is also a place where there could be duplications - a field can be desired and also sample-specific - so I wanted to test duplications are handled correctly there :-)

2025-01-17 09:57 UTC, anna-parker commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +            availableFields = availableFields.filter((field) => field.name !== bestMatch);
Hey! I found another issue here, so first you need to do an exact match and then only fuzzy matching, for example if I have my list of columns [geoLocAdmin3, geoLocAdmin1] then geoLocAdmin3 will get mapped to geoLocAdmin1 and geoLocAdmin1 will get mapped to geoLocAdmin2, see example below where I did this on the preview: 

![image](https://github.com/user-attachments/assets/07150d5b-754b-4ae9-8836-05a157c0657e)

It might also make sense to mark which fields have not been mapped exactly (e.g. score under 1) with a different color so that the user will quickly see that this mapping happened - otherwise they might miss sth being mapped incorrectly

2025-01-17 14:22 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
> +                columns in your file to the fields expected by the database.
https://github.com/loculus-project/loculus/pull/3478/commits/f21819012be66a90789dacc8ad1603ab893a94a2

2025-01-17 14:25 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +    }
https://github.com/loculus-project/loculus/pull/3478/commits/be7b42dfeeb693ddb120b95cc9a40b2c1091b88b

2025-01-17 14:26 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +    }
That is very good to know!

2025-01-17 14:27 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +    public update(newSourceColumns: string[], inputFields: InputField[]): ColumnMapping {
https://github.com/loculus-project/loculus/pull/3478/commits/d8d1616fa42ab8bc048a70c0ed016472a9ab8b5c

2025-01-17 14:29 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
> +            )}
true!

https://github.com/loculus-project/loculus/pull/3478/commits/e8f4f31983cc82e207dd16d548fb6c19ee6af88c

2025-01-17 16:26 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +            availableFields = availableFields.filter((field) => field.name !== bestMatch);
Ha! I had a murky feeling about the mapping, good think you spotted it. I've fixed it now. Also the non-exact matches are not in italic, does that work?

2025-01-17 16:26 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +            availableFields = availableFields.filter((field) => field.name !== bestMatch);
I also added all the 'desired' flags!

2025-01-17 16:26 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +        const inputRows = text.trim().split('\n');
update: used a different lib.

2025-01-19 17:42 UTC, rneher commented
I like the new UI. I would probably prefer if the required and desired fields would not be there twice. But not blocking.

2025-01-20 10:27 UTC, chaoran-chen commented on website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
> +                                    <th className='pr-16 py-2'>Column in your file</th>
The mobile view still isn't really good but agree that it's not a priority, so no need to work on it for now.

2025-01-20 10:53 UTC, anna-parker commented on website/src/components/Submission/FileUpload/ColumnMapping.ts
> +            availableFields = availableFields.filter((field) => field.name !== bestMatch);
Thanks it looks great!

2025-01-20 12:22 UTC, anna-parker commented on website/src/components/Submission/FileUpload/UploadComponent.tsx
> +    // TODO It feels like it would be useful to return a ProcessedFile here, so we know if it's compressed or not etc.
can this TODO be removed now?

2025-01-20 13:06 UTC, anna-parker commented on website/src/components/Submission/FileUpload/UploadComponent.tsx
> +    // TODO It feels like it would be useful to return a ProcessedFile here, so we know if it's compressed or not etc.
There seems to be some issues with uploading .gz files with these changes (.gz files are still working on main): 
![image](https://github.com/user-attachments/assets/bf31945a-d66b-48fe-ad33-69503bca82df)

2025-01-21 15:28 UTC, fhennig commented
@corneliusroemer In the monday meeting you said you wanted to have a look, and this is arguably a non-trivial PR; Your input is appreciated!

Chaoran already said he's fine with how things are, I've adress all of Richards points and I think all the compression related stuff that Anya mentioned is also sorted out.

2025-01-21 16:06 UTC, anna-parker commented on website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
> +        // there is potential to optimize: don't read the whole file, just the header (read in chunks)
is this an open TODO or can it be removed?

2025-01-21 16:28 UTC, anna-parker approved these changes
LGTM! 

I tested with metadata in all zip combinations except for `.xz` and this works, I also tried out some column renaming and read through the code. I'm not a typescript expert but everything looks very good and the feature is working really nicely!

2025-01-21 17:15 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
> +        // there is potential to optimize: don't read the whole file, just the header (read in chunks)
I didn't write TODO because I didn't intend _to do_ it (😄)  but thought it'd still be a good note to have there. But maybe I just remove it, I guess from the code it's obvious that this improvement could be made; and the whole file will still be read later in the process anyways, so we wouldn't even gain that much. i'll remove it.

2025-01-22 10:38 UTC, fhennig commented on website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
> +        // there is potential to optimize: don't read the whole file, just the header (read in chunks)
removed: https://github.com/loculus-project/loculus/pull/3478/commits/49108a0f9f438b9b8790b0b6735c4e7b2a574a88

2025-01-22 10:38 UTC, merged